### PR TITLE
fixed extra slash in /api makeRequest

### PR DESCRIPTION
**Pull request by www0z0k**
fix for https://github.com/luzzif/binance-api-client/issues/122
(just in case it's not only in my environment)

### CODE REVIEW

**Comment by luzzif** [comment]
Hey man, thanks for the contribution. I think it's great not to have the build folder in the actual library published on NPM. I'd fix the thing by simply using the `postinstall` hook in the `package.json`. Basically, you want to run `npm run build` on `postinstall`, and not on `prepublishOnly`, like now. Can you please add it it the PR and remove the build folder again?

**Comment by www0z0k** [comment]
So should I just rename the `prepublishOnly` script to `postinstall` (and add the build folder back to `.gitignore`)?

**Comment by luzzif** [comment]
> So should I just rename the `prepublishOnly` script to `postinstall` (and add the build folder back to `.gitignore`)? 

Exactly

**Comment by luzzif** [comment]
LGTM. Thanks for the contribution!

**Pull request merged**
